### PR TITLE
Add aborting to other tabix-js methods

### PR DESCRIPTION
**Pull request by garrettjstevens**
@cmdcolin I tried adding aborting to the `readfile`s. Let me know if this works for you.

### CODE REVIEW

**Comment by cmdcolin** [comment]
Thanks for doing this. One thing I am wondering is if this will play nicely with tinyMemoize. I haven't thought about it too much but I know this.parse for the index is added to tinyMemoize

**Comment by rbuels** [comment]
could probably just replace the tinymemoize silliness with a small abortable-promise-cache, it doesn't have much overhead

**Comment by cmdcolin** [comment]
probably true. We could use this abortable memoize https://github.com/GMOD/bbi-js/blob/master/src/bbi.ts#L55-L90 or just base the memoize off of abortable-promise-cache

**Comment by garrettjstevens** [comment]
@rbuels just to make sure you realize it, this PR was merged into the add_aborting branch and not master

**Comment by rbuels** [comment]
yeah i saw that I merged it from there into master

**Pull request merged**
