### PR TITLE
WIP: Fix fileOffset when non-ascii characters are present

### LINKED ISSUE #7: fileOffset not correct when non-ascii characters are present
Because the code uses `line.length` to advance the fileOffset, it doesn't advance enough when there are non-ascii characters, since their byte length is longer than their string length.

See failing test for this in the non_ascii branch.

### PR DESCRIPTION
**Pull request by garrettjstevens**
Eventually this PR should resolve #7 

Right now it just adds a test that fails for this case. Will add more more commits when the proper fix is determined.

### CODE REVIEW

**Comment by cmdcolin** [comment]
This would be closed following #52

**Comment by cmdcolin** [comment]
Note that the zipped offset will never correspond to the actual uncompressed file offset so this will never pass. This is an important notion in the virtual offset concept. Nevertheless we should develop some methods to take non-ascii into account. If we want to be correct for feature IDs, which some code does rely on, we should do ascii decoding and not do utf8 decoding for now

**Comment by cmdcolin** [comment]
I say close for now, since as noted above, the fileOffset is not a true offset its a virtual offset. Also I tested adding some non-ascii to a larger VCF file (https://s3.amazonaws.com/1000genomes/phase3/integrated_sv_map/ALL.wgs.integrated_sv_map_v2.20130502.svs.genotypes.vcf.gz) and making artificially large VCF features e.g. 30,000,000 bp long features and it stayed in tact (not broken across boundaries)

**Comment by garrettjstevens** [comment]
> Note that the zipped offset will never correspond to the actual uncompressed file offset so this will never pass.

I'm not sure what you mean by this. If I replace the non-ascii text in the test with ascii text, it passes just fine.

**Comment by cmdcolin** [comment]
My understanding is that it is not possible to refer to actual file offsets based on virtual file offsets

This comes from how virtual file pointers work

Part of the virtual offset pointer refers to the location of the file offset in the compressed file
The other part of the virtual offset pointer refers to the location, after uncompressing a bgzip block, within that block

We cannot recover actual uncompressed file coordinates from these

I took pains to make file offset based IDs work even under this constraint though, which I can detail further if it helps

**Comment by cmdcolin** [comment]
IIRC The small file test can be deceiving because in this case the first block has compressed file offset 0 e.g. the chunk is this

      [ Chunk {
          minv: VirtualOffset { blockPosition: 0, dataPosition: 128 },
          maxv: VirtualOffset { blockPosition: 225, dataPosition: 0 },
          bin: 4681,
          _fetchedSize: undefined } ]

**Pull request closed without merging**
