### PR TITLE
Use canMergeChunks for of index blocks calculation to avoid too large of blocks

### PR DESCRIPTION
**Pull request by cmdcolin**
This adds the canMergeBlocks from bam-js to tabix to avoid too large of blocks being downloaded

### CODE REVIEW

**Comment by cmdcolin** [comment]
Fixes #118

**Comment by rbuels** [comment]
Any reason this is still draft?

**Comment by cmdcolin** [comment]
I make everything draft by default currently

**Comment by cmdcolin** [comment]
It is probably good to go here though

**Pull request merged**
